### ISSUE TITLE
botsv2 full dataset seems corrupted

### ISSUE THREAD

**Issue by TheFausap** [splunk/botsv2#1]
Hello,
Please, could you verify the full dataset file, because I tried two times to download but, in the end, it has been corrupted in some way?
My MD5 is: c92ef55824a52541b336eb644783f256

I also performed a test of gzip archive and I got a corrupted data at 97%.

thanks
Fausto

**Comment by timip** [comment]
I just downloaded full dataset file without problem.

$ md5sum botsv2_data_set.tgz
b9ddea9c2667348d45810ef1d260897a  botsv2_data_set.tgz
